---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME-deployment
  labels: &labels
    name: "$APP_NAME-app"
    environment: "$ENV"
    application: "$APP_NAME"
spec:
  selector:
    matchLabels:
      name: $APP_NAME-app
  replicas: 1
  progressDeadlineSeconds: 300
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: $APP_NAME-app
          image: $REGISTRY_USERNAME/$APP_NAME:$BUILD_VERSION
          ports:
            - containerPort: 8080
              name: server
          resources:
            requests:
              cpu: "250m"
            limits:
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME-service
  labels:
    name: "$APP_NAME"
    environment: "$ENV"
    application: "$APP_NAME"
spec:
  type: NodePort
  selector:
    name: $APP_NAME-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
